# Generated by Django 4.2 on 2024-10-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_remove_transfer_transfer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
